title: Symposium AI in medical research
description: A symposium designed for PhDs, postdocs, and anyone interested in translating AI research into clinical impact. Aimed to bring researchers together, promote interdisciplinary collaboration, build a community, and support researchers at different stages of AI integration. 

show_downloads: true
google_analytics:
theme: jekyll-theme-cayman